# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.
language: rust
dist: xenial
sudo: required
cache: cargo

env:
  global:
  - CRATE_NAME=github-cache-rs

matrix:
  fast_finish: true

  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

deploy:
  api_key:
    secure: "M/ai4zke0IXjxEKltwVma7dghoX1qs0UfedIa3oMqEmq1bufYqlXhKgGn9ejf6s1qBla9K0SnqF/cS9VwTMWP7lknLOhWEalFTFw6w7JTKaukHEGTlwfqphW+WXeNG09ZhTotkJeGAnmIMHZZ0Ek+20wfzHtYbtENG1P0vjNZ/id8x1+8R1ZoCu4XHSNpuGklURJVfffHF6XmLOg1TInnT69jnw8OpfMRjK4bo0Y+6xM/yx1o+c9U24S9YCVvb0SIQ10pSdvfi9ik5M6AgU6K6Xqobl/jRwMfzWNrmgP3LHc8XcA/iVRxYNDpGqY2tpfbihIaB3jl4sKPzHa4nS8UbEI+CHqI65wc+d7YQ6B/ZGq2Vrr3psPDqrWsrSJseiqLWSZgCirc31ynw6khtkwdD7ygQZS0zcbqMPNh15lmdd3CFENpil/spmAxhHgw2CUxdPQmk3SIx4CR5HD7yITPAtgUAljQ2ZbEfU6DkddJa5tBnnLDB4n/72r8nO/uRVEv/dj30e6r1flWQcJz1cUcJSzXmWSSqMkir4Hk6hwC3yIeZbaUaaEHy04zouzwq+IQ349koRuDSdGxEFyELoiXx+W96LoYIktDiADIb8HV9dCvXNv8eKfURoRLBd+HDneOQCuu5juXHkxk7gypV0cLTpQ5/LuW75mTIXNECkmQuc="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION=nightly
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
