name: Release

on: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        env:
          TARGET: x86_64-unknown-linux-musl
        run: cargo build --release --verbose --target $TARGET
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/github-cache-rs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
